"""empty message

Revision ID: 959381fe796f
Revises: ae93c5d3dd4e
Create Date: 2021-05-26 01:01:46.664515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959381fe796f'
down_revision = 'ae93c5d3dd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
