"""empty message

Revision ID: a761ec950bbe
Revises: dcc74ad67080
Create Date: 2021-05-29 01:51:54.576358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a761ec950bbe'
down_revision = 'dcc74ad67080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('students', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
