"""empty message

Revision ID: dcc74ad67080
Revises: 959381fe796f
Create Date: 2021-05-28 02:37:18.147587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc74ad67080'
down_revision = '959381fe796f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('students', 'name')
    # ### end Alembic commands ###
